[[remotes]]
name = "origin"
url = "git@github.com:fluendo/gstreamer.git"

[[remotes]]
name = "freedesktop"
url = "git@ssh.gitlab.freedesktop.org:gstreamer/gstreamer.git"

[target]
remote = "origin"
branch = "gst.wasm"

[source]
remote = "origin"
branch = "wasm-main-base"

[[features]]
remote = "origin"
name = "meson_fix_nls"
summary = "Use nls option to set ENABLE_NLS"
pr = "https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/7017"
status = "integrated"

[[features]]
remote = "origin"
name = "RDI-3208-thread-func-return"
summary = "GThreadFunc return type fixes"
pr = "https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/10682"
status = "pending" # TODO: Remove this feature after wasm-main-base sync with upstream.

[[features]]
remote = "origin"
name = "wasm-main-enable"
summary = "Enable support for wasm"
status = "pending"

[[features]]
remote = "origin"
name = "wasm-main-test"
summary = "Enable unit tests for wasm"
status = "pending"

[[features]]
remote = "origin"
name = "wasm-main-openal"
summary = "Add emscripten support OpenAL to play audio"
status = "pending"

[[features]]
remote = "origin"
name = "wasm-main-gl-support"
summary = "Add emscripten OpenGL backend"
status = "pending"

[[features]]
name = "wasm-main-webtransport"
remote = "origin"
status = "pending"

[[features]]
remote = "origin"
name = "wasm-main-wip"
summary = "Commits in progress"
status = "pending"

[[features]]
name = "wasm-main-dash"
remote = "origin"
status = "pending"

[[features]]
remote = "origin"
name = "libav-add-element-groups"
summary = "Add element_groups meson option to gst-libav"
status = "pending"
pr = "https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/8877"

[[features]]
remote = "origin"
name = "fix-disable-mse"
summary = "libs: mse: Disable if mse option disabled"
status = "pending"
pr = "https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/11467"
