name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'build/**'
      - 'gst.wasm/**'
      - '.github/workflows/build.yaml'
  pull_request:
    branches:
      - '**'
    paths:
      - 'build/**'
      - 'gst.wasm/**'
      - '.github/workflows/build.yaml'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps: # these steps are used in README.md to describe preparation; keep in-sync, please!
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Clone cerbero
        run: |
          git clone https://github.com/fluendo/cerbero cerbero-src -b gst.wasm --depth=1
      - name: Bootstrap
        run: |
          ./cerbero-src/cerbero-uninstalled -c build/gst.wasm.cbc bootstrap
      - name: Build dependencies
        run: |
          ./cerbero-src/cerbero-uninstalled -c build/gst.wasm.cbc build-deps gst.wasm
      - name: Build gst.wasm
        run: |
          ./cerbero-src/cerbero-uninstalled -c build/gst.wasm.cbc build gst.wasm
      - name: Create tarball
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          tar -cvJf gst.wasm.tar.xz -C build/gst.wasm_web_wasm32/dist/web_wasm32 -c .
      - name: Upload gst.wasm
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v4
        with:
          name: gst.wasm
          path: gst.wasm.tar.xz
