name: GStreamer Build

on:
  push:
    branches:
      - main
    paths:
      - 'cerbero/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'cerbero/**'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Clone cerbero
        run: |
          git clone https://github.com/fluendo/cerbero cerbero-src -b gst.wasm --depth=1
      - name: Bootstrap
        run: |
          ./cerbero-src/cerbero-uninstalled -c cerbero/gst.wasm.cbc bootstrap
      - name: Build GStreamer
        run: |
          ./cerbero-src/cerbero-uninstalled -c cerbero/gst.wasm.cbc build gst-plugins-base-1.0 gst-plugins-good-1.0 gst-plugins-bad-1.0
      - name: Build samples
        run: |
          ./cerbero-src/cerbero-uninstalled -c cerbero/gst.wasm.cbc build gst.wasm-samples
      - name: Create tarball
        run: |
          tar -cvJf gst.wasm.tar.xz -C cerbero/build/gst.wasm_linux_web_wasm32/dist/web_wasm32/ -c .
      - name: Upload gst.wasm
        uses: actions/upload-artifact@v4
        with:
          name: gst.wasm
          path: gst.wasm.tar.xz
